### ISSUE TITLE
Untranslated lines that start with 2 or more numbers is ignored by the translation tool.

### ISSUE THREAD

**Issue by F310N** [LoneDev6/GarageDoor#1]
There is a note that you receive in the game with several lines that start with 3 numbers and the translation tool ignores the lines. Even if the lines were added into the translation.ini file manually, the lines would still be ignored and untranslated in the game.

**Comment by LoneDev6** [comment]
Should be fixed in latest release https://github.com/LoneDev6/GarageDoor/releases/tag/0.0.2
