### ISSUE TITLE
No "GarageOpener.exe" included in the English patch

### ISSUE THREAD

**Issue by Mephistople** [LoneDev6/GarageDoor#4]
Hi
According to the read-me you are supposed to launch the GarageOpener.exe to play the game.
But no such file is included in the GarageEnglishPatch.7z.
I assume this is just a small oversight, thanks again for the translation :)
![No GarageOpener](https://user-images.githubusercontent.com/53997310/118134184-2ab61b80-b3f1-11eb-9a5b-71b347c85304.png)

**Comment by LoneDev6** [comment]
Thanks!
Sorry I surely forgot to include it, no idea why.
https://mega.nz/file/NBkDFagI#_FTZ-RPG-bAafelRs0dnG7HmNL0FBTDYZcH-gI1N2JI
