### ISSUE TITLE
question about tool (not issues)

### ISSUE THREAD

**Issue by YouKnow-sys** [LoneDev6/GarageDoor#6]
Hi, sorry if its not related to this project 😅

I wonder how you managed to change game text in run time  
there is a game name Total overdose that I love to translate, but sadly I cant find any way to reverse the game file itself, file format is so complicated and I cant understand it  
I think my best bet is to translate the game when decrypted text stored in game memory, but Im not sure how...  
can you give me some information about it? thank you.

**Comment by LoneDev6** [comment]
I used CheatEngine to find out the game function which writes on screen, then coded a detour and added my own logic
